services:
  store_manager:
    build: .
    container_name: store_manager
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    networks:
      - labo05-network
    depends_on:
      - mysql
      - redis

  locust:
     image: locustio/locust
     ports:
       - "8089:8089"
     volumes:
       - ./locustfiles:/mnt/locust
     command: -f /mnt/locust/locustfile.py --host=http://api-gateway:8080
     depends_on:
      - store_manager
     networks:
       - labo05-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - labo05-network
    depends_on:
      - store_manager

  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: labo04_db
      MYSQL_USER: labo04
      MYSQL_PASSWORD: labo04
    networks:
      - labo05-network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    restart: unless-stopped
    networks:
      - labo05-network
    ports:
      - "6379:6379"

  krakend:
    image: devopsfaith/krakend:2.4
    container_name: api-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./config/krakend.json:/etc/krakend/krakend.json
    networks:
      - labo05-network
    depends_on:
      - store_manager

networks:
  labo05-network:
    external: true

volumes:
  mysql_data:
  prometheus_data:
