name: Deploy (Self-Hosted)

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Create/Update .env
        run: |
          cat > .env << 'EOF'
          DB_HOST=mysql
          DB_PORT=3306
          DB_NAME=labo04_db
          DB_USER=labo04
          DB_PASS=labo04
          REDIS_HOST=redis
          REDIS_PORT=6379
          REDIS_DB=0
          EOF

      - name: Pull & build
        run: |
          docker compose pull || true
          docker compose build --no-cache

      - name: Create network
        run: docker network create labo05-network || true

      - name: Up app
        run: |
          docker compose up -d --remove-orphans

      - name: Show status
        run: |
          docker compose ps
          docker compose logs -n 100 store_manager || true